version: "3"
services:
    dotfiles-vm:
        build: dotfiles-vm
        container_name: "dotfiles-vm"
        tty: true
        # start_setting.shが正常終了するか
        # vint .vimrcの構文チェック
        # grunt .zshrcの構文チェック
        # 2回start_setting.shを動かしても同じ結果になるか
        # シンボリックリンクを貼っている各種設定ファイルに破損がないかチェック
        command: >
            zsh -c "cd /root/dotfiles;
            ./start_setting.sh;
            if [ `md5sum /root/dotfiles/zshrc | awk '{print $$1}'` = `md5sum /root/.zshrc | awk '{print $$1}'` ] &&
            [ `md5sum /root/dotfiles/vimrc | awk '{print $$1}'` = `md5sum /root/.vimrc | awk '{print $$1}'` ];
            then echo Done; else exit 1; fi;
            ./start_setting.sh;
            ./start_setting.sh;
            if [ `md5sum /root/dotfiles/zshrc | awk '{print $$1}'` = `md5sum /root/.zshrc | awk '{print $$1}'` ] &&
            [ `md5sum /root/dotfiles/vimrc | awk '{print $$1}'` = `md5sum /root/.vimrc | awk '{print $$1}'` ];
            then echo Done; else exit 1; fi;
            ./start_setting.sh;
            vint /root/.vimrc;
            grunt zshlint;"
